lookupA: "{{ lookup('lookup', 'lookupA') }}"
lookupB: "{{ lookup('lookup', 'lookupB') }}"
lookupC: "{{ lookup('lookup', 'lookupC') }}"
lookupD: "{{ lookup('lookup', 'lookupD') }}"
lookupF: "{{ lookup('lookup', 'lookupF') }}"
lookupG: "{{ lookup('lookup', 'lookupG') }}"
lookupH: "{{ lookup('lookup', 'lookupH') }}"
lookupI: "{{ lookup('lookup', 'lookupI') }}"
lookupJ: "{{ lookup('lookup', 'lookupJ') }}"
lookupK: "{{ lookup('lookup', 'lookupK') }}"
lookupL: "{{ lookup('lookup', 'lookupL') }}"
lookupM: "{{ lookup('lookup', 'lookupM') }}"
lookupN: "{{ lookup('lookup', 'lookupN') }}"
lookupO: "{{ lookup('lookup', 'lookupO') }}"
lookupP: "{{ lookup('lookup', 'lookupP') }}"
lookupQ: "{{ lookup('lookup', 'lookupQ') }}"
lookupR: "{{ lookup('lookup', 'lookupR') }}"
lookupS: "{{ lookup('lookup', 'lookupS') }}"
lookupT: "{{ lookup('lookup', 'lookupT') }}"
lookupU: "{{ lookup('lookup', 'lookupU') }}"
lookupV: "{{ lookup('lookup', 'lookupV') }}"
lookupW: "{{ lookup('lookup', 'lookupW') }}"
lookupX: "{{ lookup('lookup', 'lookupX') }}"
lookupY: "{{ lookup('lookup', 'lookupY') }}"
lookupZ: "{{ lookup('lookup', 'lookupZ') }}"
